### ISSUE TITLE
Service based filtering seems to be broken

### ISSUE THREAD

**Issue by sstalle** [rdohms/DMS#49]
When service filter annotation

```
@SfFilter\Service(service="foo", method="bar")
```

is defined for submitted entity's field, the following exception is thrown on form submission: "Unable to locate filter for: dms.filter.container_filter defined in DMS\Bundle\FilterBundle\Rule\Service".

Looks like dms.filter.container_filter service is not defined anywhere, because adding

```
dms.filter.container_filter:
    class: DMS\Bundle\FilterBundle\Filter\ContainerFilter
    calls:
        - [setContainer, [@service_container]]
```

to app/config/config.yml solves the issue.
